name: Python CI (Venv)

on:
  push:
    branches:
      - main
      - ajout-tests-ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/Scripts/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        .venv\Scripts\activate
        pytest tests/
