name: Python CI

on:
  push:
    branches:
      - main
      - ajout-tests-ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: List all files (Windows-compatible)
      run: dir /s

    - name: Print current working directory (Windows-compatible)
      run: cd

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 3_dossier_code_012025/requirements.txt

    - name: Run tests
      run: |
        pytest 3_dossier_code_012025/tests/
