name: Python CI

on:
  push:
    branches:
      - main
      - ajout-tests-ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Utilisation de Windows pour correspondre à l'environnement local

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Print current directory and list files
      run: |
        echo "Current directory:"
        pwd
        echo "Contents:"
        ls -al

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Pour Linux, remplacez ls par "dir /s"

    - name: Run tests
      run: |
        pytest 3_dossier_code_012025/tests/
