name: Deploy to Azure

on:
  push:
    branches:
      - main
      - api-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilisation d'Ubuntu pour compatibilité avec Azure Actions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        # pip install -r <(grep -vE "pywin32|pywinpty" requirements.txt)
        pip install gunicorn

    # - name: Remove Windows-specific dependencies
    #   run: |
    #     sed -i '/^pywin32==/d' requirements.txt
    #     sed -i '/^pywinpty==/d' requirements.txt

    - name: Start API for testing
      run: |
        source .venv/bin/activate
        python api./app.py &  # Lance l'API en arrière-plan
        sleep 5  # Donne du temps à l'API pour démarrer

    - name: Run unit tests
      run: |
        source .venv/bin/activate
        pytest tests/test_api.py

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: .

    - name: Wait for API to be ready
      run: |
        for i in {1..10}; do
          if curl -s --head --fail "https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net"; then
            echo "API is up!"
            exit 0
          fi
          echo "Waiting for API..."
          sleep 10
        done
        echo "API did not start in time" && exit 1

    - name: Test deployed API
      run: |
        curl -X POST "https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net/predict" \
        -H "Content-Type: application/json" -d '{}'
